{{- if and (include "choreo-connect.deploymentMode.isStandalone" .) .Values.wso2.ingress.adapter.enabled }}
# Copyright (c) 2022, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-ingress" (include "choreo-connect.adapterFullname" .) | trunc 63 }}
  namespace: {{ .Release.Namespace }}
{{- with .Values.wso2.ingress.adapter.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  tls:
  - hosts:
      - {{ .Values.wso2.ingress.adapter.hostname }}
  {{- if .Values.wso2.ingress.adapter.tlsSecretName }}
    secretName: {{ .Values.wso2.ingress.adapter.tlsSecretName }}
  {{- else }}
    secretName: {{ printf "%s-ingress-tls-secret" (include "choreo-connect.fullname" .) | trunc 63 }}
  {{- end }}
  rules:
    - host: {{ .Values.wso2.ingress.adapter.hostname }}
      http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: {{ include "choreo-connect.adapterFullname" . | quote }}
                  port:
                    number: 9843
{{- end -}}
