{{- if .Values.wso2.deployment.gatewayRuntime.autoscaling.enabled }}
# --------------------------------------------------------------------
# Copyright (c) 2022, WSO2 Inc. (http://wso2.com) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# -----------------------------------------------------------------------

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{printf "%s-%s" (include "choreo-connect.fullname" .) "gateway-runtime" | trunc 63 }}
  namespace: {{ .Release.Namespace }}
  annotations:
    autoscaling.alpha.kubernetes.io/metrics: '[{"type":"Resource","resource":{"name":"memory","targetAverageUtilization":{{ .Values.wso2.deployment.gatewayRuntime.autoscaling.targetMemoryUtilizationPercentage }}}}]'
  labels:
    {{- include "choreo-connect.labels" . | nindent 4 }}
    app.kubernetes.io/component: choreo-connect-gateway-runtime
spec:
  maxReplicas: {{ .Values.wso2.deployment.gatewayRuntime.autoscaling.maxReplicas }}
  minReplicas: {{ .Values.wso2.deployment.gatewayRuntime.autoscaling.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{printf "%s-%s" (include "choreo-connect.fullname" .) "gateway-runtime" | trunc 63 }}
  targetCPUUtilizationPercentage: {{ .Values.wso2.deployment.gatewayRuntime.autoscaling.targetCPUUtilizationPercentage }}
{{- end -}}
