{{- if .Values.wso2.deployment.gatewayRuntime.router.ingress.enabled }}
# --------------------------------------------------------------------
# Copyright (c) 2022, WSO2 Inc. (http://wso2.com) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# -----------------------------------------------------------------------

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-router" (include "choreo-connect.fullname" .) | trunc 63 }}
  namespace: {{ .Release.Namespace }}
{{- with .Values.wso2.deployment.gatewayRuntime.router.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  {{- if .Values.kubernetes.ingress.className }}
  ingressClassName: {{ .Values.kubernetes.ingress.className }}
  {{- end }}
  tls:
  - hosts:
      - {{ .Values.wso2.deployment.gatewayRuntime.router.ingress.hostname }}
  {{- if .Values.wso2.deployment.gatewayRuntime.router.ingress.tlsSecretName }}
    secretName: {{ .Values.wso2.deployment.gatewayRuntime.router.ingress.tlsSecretName }}
  {{- else }}
    secretName: {{ printf "%s-default-ingress-tls" (include "choreo-connect.fullname" .) | trunc 63 }}
  {{- end }}
  rules:
    - host: {{ .Values.wso2.deployment.gatewayRuntime.router.ingress.hostname }}
      http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: {{printf "%s-%s" (include "choreo-connect.fullname" .) "router" | trunc 63 | quote }}
                  port:
                    number: 9095
{{- end -}}
